# Generated by Django 6.0 on 2026-08-24 03:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_country'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique identifier for the invoice e.g., INV-20260824-1001', max_length=30, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, help_text='Date on which the invoice was issued.')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date for this invoice.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], db_index=True, default='DRAFT', help_text='Current settlement and billing status of the invoice.', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI Payment'), ('CREDIT_CARD', 'Credit Card'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Store Credit / Account')], default='CASH', help_text='Mode of payment agreed or received.', max_length=30)),
                ('payment_terms', models.CharField(blank=True, default='Net 30', help_text='Standard terms of payment (e.g. Due on Receipt, Net 15, Net 30).', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line item totals before taxes and overall discount.', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total calculated Goods & Services Tax (GST) across all items.', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overall invoice-level discount applied to total bill.', max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final payable invoice amount inclusive of GST and discounts.', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payments collected against this invoice.', max_digits=12)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes or customer-visible memo.')),
                ('terms_and_conditions', models.TextField(blank=True, default='Thank you for your business! Payment is due according to agreed terms.', help_text='Standard legal terms, refund policies, or payment instructions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User or distributor who generated this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer or billing account linked to this invoice.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of product purchased.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit selling price at time of billing (excl. GST).', max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Applicable Goods & Services Tax (GST) rate percentage.', max_digits=5)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line item discount percentage (0 to 100%).', max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line subtotal before GST (unit_price * quantity).', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated GST tax amount for this line item.', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated net total amount for this line item (subtotal + tax - discount).', max_digits=12)),
                ('description', models.TextField(blank=True, default='', help_text='Optional custom description or serial numbers for this line item.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Parent invoice associated with this line item.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(help_text='Product or inventory item billed in this line.', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['id'],
            },
        ),
    ]
