# Generated by Django 6.0 on 2026-08-23 04:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Unique Product SKU code (e.g., PRD-1001).', max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Full product title or item name.', max_length=255)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics & Hardware'), ('Office Supplies', 'Office Supplies & Stationery'), ('Groceries', 'Groceries & FMCG'), ('Apparel', 'Apparel & Clothing'), ('Industrial', 'Industrial & Electrical'), ('Services', 'Services & Maintenance'), ('General', 'General Goods')], default='General', help_text='Primary product classification category.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit selling price before GST tax (in INR).', max_digits=12)),
                ('stock', models.IntegerField(default=0, help_text='Current available inventory quantity in stock.')),
                ('gst_rate', models.DecimalField(choices=[(Decimal('0.00'), '0% (Exempt)'), (Decimal('5.00'), '5% (Essential Goods)'), (Decimal('12.00'), '12% (Standard Low)'), (Decimal('18.00'), '18% (Standard Rate)'), (Decimal('28.00'), '28% (Luxury / Premium)')], decimal_places=2, default=Decimal('18.00'), help_text='Applicable Goods & Services Tax (GST) rate percentage.', max_digits=5)),
                ('hsn_code', models.CharField(blank=True, default='', help_text='Harmonized System Nomenclature (HSN) code for GST invoicing.', max_length=20)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces (pcs)'), ('box', 'Box (box)'), ('kg', 'Kilograms (kg)'), ('ltr', 'Liters (ltr)'), ('mtr', 'Meters (mtr)'), ('set', 'Set (set)'), ('pack', 'Pack (pack)')], default='pcs', help_text='Unit of measurement (e.g., pcs, kg, box).', max_length=20)),
                ('min_stock_level', models.IntegerField(default=10, help_text='Minimum stock threshold to trigger low stock alerts.')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed product specifications, feature notes, or comments.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this product is active and available for billing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
