# Generated by Django 6.0 on 2026-08-20 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Contact phone number of the distributor.', max_length=20)),
                ('company_name', models.CharField(blank=True, help_text='Registered wholesale business or trade name.', max_length=255, null=True)),
                ('distributor_id', models.CharField(db_index=True, help_text='Unique Distributor Tracking Identifier e.g. DIST-8842', max_length=20, unique=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=50000.0, help_text='Maximum credit allowance.', max_digits=12)),
                ('is_verified', models.BooleanField(default=True, help_text='Distributor verification status.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distributor Profile',
                'verbose_name_plural': 'Distributor Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
