# Generated by Django 6.0 on 2026-08-21 03:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(db_index=True, help_text='Unique Identifier for Customer e.g., CUST-4821', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full contact name or primary representative name.', max_length=255)),
                ('email', models.EmailField(db_index=True, help_text='Primary notification & invoicing email address.', max_length=255)),
                ('phone', models.CharField(help_text='Primary telephone or mobile number.', max_length=20)),
                ('company_name', models.CharField(blank=True, help_text='Registered company or business entity name (optional).', max_length=255, null=True)),
                ('address', models.TextField(help_text='Street address, building number, or billing location.')),
                ('city', models.CharField(blank=True, default='', help_text='City or town.', max_length=100)),
                ('state', models.CharField(blank=True, default='', help_text='State, province, or region.', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', help_text='ZIP or postal code.', max_length=20)),
                ('country', models.CharField(default='India', help_text='Country location.', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax Registration ID or GSTIN number (optional).', max_length=50, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Maximum allowed credit for deferred billing transactions.', max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current unsettled balance.', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this customer account is active.')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes or special instructions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(blank=True, help_text='Distributor account managing this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
