# Generated by Django 6.0 on 2026-08-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applicable Goods & Services Tax (GST) rate percentage. Defaults to Product GST rate if left blank.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit selling price at time of billing (excl. GST). Defaults to Product price if left blank.', max_digits=12, null=True),
        ),
    ]
